Update gpg-login and aliases for sandbox commands

diff --git a/bin/gpg-login b/bin/gpg-login
--- a/bin/gpg-login
+++ b/bin/gpg-login
@@ -1,11 +1,20 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
 
-pkill gpg-agent || true
-if echo "test" | gpg --clearsign &> /dev/null ; then
-    echo "gpg-login successful"
-else
-    exitcode=$?
-    echo "gpg-login failed"
-    exit "$exitcode"
+# Key already cached in memory?
+RESULT=$(gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | \
+    awk 'BEGIN{CACHED=0} /^S/ {if($7==1){CACHED=1}} END{if(NR>0){print CACHED} else {print "none"}}')
+if [[ "$RESULT" == "1" ]]; then
+    echo >&2 "gpg-login cached"
+    exit 0
 fi
+
+pkill gpg-agent || true
+if ! echo "test" | gpg --clearsign &> /dev/null ; then
+    echo >&2 "gpg-login failed"
+    exit 1
+fi
+
+
+echo >&2 "gpg-login successful"
+exit 0
