Update to modern bash on OSX
Fix all scripts to use env to locate bash

diff --git a/.dotfiles/ssh-agent b/.dotfiles/ssh-agent
--- a/.dotfiles/ssh-agent
+++ b/.dotfiles/ssh-agent
@@ -1,4 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+    echo >&2 "ERROR: This script must be sourced"
+    exit 1
+fi
 
 # Note: ~/.ssh/environment should not be used, as it
 #       already has a different purpose in SSH.
